version: "3.8"
services:
  db:
    image: postgres:14
    container_name: db
    volumes:
      - disk-api-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: disk-api
      POSTGRES_PASSWORD: password

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: disk-api-image
    container_name: disk-api-app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/disk-api
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password

    ports:
      - "80:8080"
volumes:
  disk-api-db-data:
    name: disk-api-db-data
